version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - database
        ports:
            - "9100:9100"
        networks:
            - default
    database:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=database
            - DATABASE_HOST=localhost
        ports:
            - "5432"
        command: -p 5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -p postgres -h database -p 5432"]
            interval: 5s
            timeout: 5s
            retries: 10
        volumes:
            - ./data:/var/lib/postgresql/data
            - ./init_stockbit.sql:/docker-entrypoint-initdb.d/data.sql
        networks:
            - default
volumes:
    data:
